### AI-0102 Practice 2

**1.**  

In [1]:
import numpy as np

**2.**  

In [2]:
v4 = np.arange(1, 9)
print( v4 )

[1 2 3 4 5 6 7 8]


**3.**  

In [3]:
print( v4.shape )

(8,)


**4.**  

In [4]:
v5 = v4.reshape( 2, 4 )
# どちらか一方を -1 にして自動計算させてもよい  
# v5 = v4.reshape( -1, 4 )  
# v5 = v4.reshape( 2, -1 )  
print( v5 )

[[1 2 3 4]
 [5 6 7 8]]


**5.**  

In [5]:
print( v5.shape )

(2, 4)


**6.**  

In [6]:
print( np.amin( v5, axis=1 ) )

[1 5]


**7.**  

In [7]:
print( np.sum( v5, axis=0 ) )

[ 6  8 10 12]
