In [1]:
import numpy as np

In [2]:
v1 = np.array([1,3,5,7,9,7,5,3,1])

In [3]:
v2 = v1.reshape(3, -1)

In [4]:
print(v2.shape)
print(v2)

(3, 3)
[[1 3 5]
 [7 9 7]
 [5 3 1]]


In [5]:
np.amax( v2, axis=1 )

array([5, 9, 5])

In [6]:
np.mean( v2, axis=0 )

array([4.33333333, 5.        , 4.33333333])