### Review of Numpy and Pandas  

See both of MOOCs and this notebook to understand the concept of this lecture.  
Each cell can be executed with Shift+Enter.  
MOOCsの説明と合わせて、内容を理解すること。  
各セルは、セル内を左クリック、Shift+Enter (ShiftキーとEnterキーを同時に押す) で実行できる。  

### Import libraries  
まずライブラリをimport  

In [1]:
import numpy as np
import pandas as pd

### How to make ndarray and its difference from list  
Numpy配列の作り方、リストとの違い  

In [2]:
lst = [0, 1, 2]
v1d = np.array(lst)

print( lst*2 )  # *2 of "list"
print( v1d*2 )  # *2 of "ndarray"

[0, 1, 2, 0, 1, 2]
[0 2 4]


### Operations between ndarrays  
Numpy配列の演算(1次元配列同士)  

In [3]:
v1 = np.array( [1.0, 2.0, 3.0] )
v2 = np.array( [2.0, 4.0, 6.0] )

print( v1+v2 )  # arithmetic(四則演算)
print( v1*v2 )
print( np.dot(v1, v2) )  # dot product

[3. 6. 9.]
[ 2.  8. 18.]
28.0


### Matrix (2-d array) multiplied by vector (1-d array)  
行列(2次元配列)とベクトル(1次元配列)の積  

In [4]:
A = np.array( [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]] )
x = np.array( [1.0, 1.0, 1.0] )
b = np.array( [2.0, 2.0] )

print( A*x )
y = np.dot(A, x) + b
print( y )

[[1. 2. 3.]
 [4. 5. 6.]]
[ 8. 17.]


### Initialization of ndarray  
Numpy配列の初期化 

In [5]:
A = np.empty(5); print(A)
A = np.empty((2,3)); print(A)
A = np.zeros((2,3)); print(A)
A = np.ones((2,3)); print(A)
A = np.identity(3); print(A)

[1.49783934e-311 6.95196142e-310 0.00000000e+000 0.00000000e+000
 2.12199580e-314]
[[1. 2. 3.]
 [4. 5. 6.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Generation of serial numbers  
連番(等差数列)の生成  

In [6]:
print( np.arange(5) )
print( np.arange(2, 8) )
print( np.arange(2, 8, 2) )
print( np.arange(1.8, -1.8, -0.9) )

print( np.linspace(-2, 2, num=5) )
print( np.linspace(-2, 2, num=5, endpoint=False) )

[0 1 2 3 4]
[2 3 4 5 6 7]
[2 4 6]
[ 1.8  0.9  0.  -0.9]
[-2. -1.  0.  1.  2.]
[-2.  -1.2 -0.4  0.4  1.2]


### Change shape of ndarray  
Numpy配列の形を変更する  

In [7]:
v1 = np.arange(6); print(v1)
v2 = v1.reshape(2, 3); print(v2)
v2 = v1.reshape(-1, 3); print(v2)
v3 = v2.T; print(v3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


### Misc operations for ndarray  
その他のNumpy配列の操作  

In [8]:
X = np.array( [[0, 1, 2], [3, 4, 5]] )
print( X.shape )
X = np.array( [0, 1, 2, 3, 4] )
print( X.shape )

X2 = X.copy()
print(X2)

(2, 3)
(5,)
[0 1 2 3 4]


### Calculation of statistics  
統計諸量の計算  

In [9]:
dat = np.array( [[0, 1, 2], [3, 4, 5]] )

# by col
print( np.amin(dat, axis=0) )
print( np.amax(dat, axis=0) )
print( np.mean(dat, axis=0) )
print( np.median(dat, axis=0) )
print( np.std(dat, axis=0) )
print( np.sum(dat, axis=0) )
print( np.std(dat, ddof=1, axis=0) )

# by row
print( np.amin(dat, axis=1) )
print( np.amax(dat, axis=1) )
print( np.mean(dat, axis=1) )
print( np.median(dat, axis=1) )
print( np.std(dat, axis=1) )
print( np.sum(dat, axis=1) )
print( np.std(dat, ddof=1, axis=1) )

[0 1 2]
[3 4 5]
[1.5 2.5 3.5]
[1.5 2.5 3.5]
[1.5 1.5 1.5]
[3 5 7]
[2.12132034 2.12132034 2.12132034]
[0 3]
[2 5]
[1. 4.]
[1. 4.]
[0.81649658 0.81649658]
[ 3 12]
[1. 1.]


### Read CSV file  
CSVファイルの読み込み  

In [10]:
df = pd.read_csv('pandas_training-utf8.csv',
                 delimiter=',', skiprows=13, header=0)

### When CSV file is too large to open with editor  
CSVファイルが巨大でエディタで開けない場合  

In [11]:
df_head = pd.read_csv('pandas_training-utf8.csv', delimiter='\n', dtype='object',
                      skiprows=None, header=None, nrows=15)
display(df_head)

0
0                 Wholesale Customers Data Set,,,,,,,
1   https://archive.ics.uci.edu/ml/datasets/wholes...
2   Abreu, N. (2011). Analise do perfil do cliente...
3                                             ,,,,,,,
4   CHANNEL(販路): customers's Channel - Horeca (Hot...
5   REGION(地域): customers's Region - Lisbon, Oport...
6   FRESH(生鮮): annual spending (m.u.) on fresh pro...
7   MILK(乳製品): annual spending (m.u.) on milk prod...
8   GROCERY(食料品): annual spending (m.u.)on grocery...
9   FROZEN(冷凍): annual spending (m.u.)on frozen pr...
10  DET_PAPER(洗剤・紙類): annual spending (m.u.) on de...
11  DELICA(惣菜): annual spending (m.u.)on and delic...
12                                            ,,,,,,,
13  CHANNEL,REGION,FRESH,MILK,GROCERY,FROZEN,DET_P...
14         Retail,Other,12669,9656,7561,214,2674,1338

### Check DataFrame  
DataFrameの確認  

In [12]:
print( df.shape )
print( df.dtypes )
display( df.info() )
display( df.describe() )
display( df.describe(exclude='number') )
display( df.head() )

(440, 8)
CHANNEL      object
REGION       object
FRESH         int64
MILK          int64
GROCERY       int64
FROZEN        int64
DET_PAPER     int64
DELICA        int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   CHANNEL    440 non-null    object
 1   REGION     440 non-null    object
 2   FRESH      440 non-null    int64 
 3   MILK       440 non-null    int64 
 4   GROCERY    440 non-null    int64 
 5   FROZEN     440 non-null    int64 
 6   DET_PAPER  440 non-null    int64 
 7   DELICA     440 non-null    int64 
dtypes: int64(6), object(2)
memory usage: 27.6+ KB


None

FRESH          MILK       GROCERY        FROZEN     DET_PAPER  \
count     440.000000    440.000000    440.000000    440.000000    440.000000   
mean    12000.297727   5796.265909   7951.277273   3071.931818   2881.493182   
std     12647.328865   7380.377175   9503.162829   4854.673333   4767.854448   
min         3.000000     55.000000      3.000000     25.000000      3.000000   
25%      3127.750000   1533.000000   2153.000000    742.250000    256.750000   
50%      8504.000000   3627.000000   4755.500000   1526.000000    816.500000   
75%     16933.750000   7190.250000  10655.750000   3554.250000   3922.000000   
max    112151.000000  73498.000000  92780.000000  60869.000000  40827.000000   

             DELICA  
count    440.000000  
mean    1524.870455  
std     2820.105937  
min        3.000000  
25%      408.250000  
50%      965.500000  
75%     1820.250000  
max    47943.000000

CHANNEL REGION
count      440    440
unique       2      3
top     Horeca  Other
freq       298    316

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

### Misc operations for Dataframe  
その他のDataFrame操作  

In [13]:
display(df.head(3))
df2 = df.copy(); display(df2.head(3))
df2 = df.rename(columns={'REGION':'area', 'CHANNEL':'ch'})
display(df2.head(3))
df2 = df.T; display(df2.head())

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

ch   area  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

0       1       2       3       4       5       6       7    \
CHANNEL  Retail  Retail  Retail  Horeca  Retail  Retail  Retail  Retail   
REGION    Other   Other   Other   Other   Other   Other   Other   Other   
FRESH     12669    7057    6353   13265   22615    9413   12126    7579   
MILK       9656    9810    8808    1196    5410    8259    3199    4956   
GROCERY    7561    9568    7684    4221    7198    5126    6975    9426   

            8       9    ...     430     431     432     433     434     435  \
CHANNEL  Horeca  Retail  ...  Horeca  Horeca  Horeca  Horeca  Horeca  Horeca   
REGION    Other   Other  ...   Other   Other   Other   Other   Other   Other   
FRESH      5963    6006  ...    3097    8533   21117    1982   16731   29703   
MILK       3648   11093  ...    4230    5506    1162    3218    3922   12051   
GROCERY    6192   18881  ...   16483    5160    4754    1493    7994   16027   

            436     437     438     439  
CHANNEL  Horeca  Retail  Horeca  Horeca  
REGION    Other   Other   Other   Other  
FRESH     39228   14531   10290    2787  
MILK       1431   15488    1981    1698  
GROCERY     764   30243    2232    2510  

[5 rows x 440 columns]

### Make Series/DataFrame from a list  
Series/DataFrameをリストから作る  

In [14]:
lst1 = [2, 4, 6]
ser1 = pd.Series(lst1); print(ser1)
lst2 = [ [2, 4, 6], [1, 3, 5] ]
df2 = pd.DataFrame(lst2); display(df2)

0    2
1    4
2    6
dtype: int64


0  1  2
0  2  4  6
1  1  3  5

### Extraction of rows  
行全体の取り出し  

In [15]:
display(df.head(3))
ser_row2 = df.loc[2]; print(ser_row2)
df_list = df.loc[[1, 3]]; display(df_list.head(3))
df_slice = df.loc[1:3]; display(df_slice.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL      Retail
REGION        Other
FRESH          6353
MILK           8808
GROCERY        7684
FROZEN         2405
DET_PAPER      3516
DELICA         7844
Name: 2, dtype: object


CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
1  Retail  Other   7057  9810     9568    1762       3293    1776
3  Horeca  Other  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

### Extraction of columns  
列の取り出し 

In [16]:
display(df.head(3))
ser_milk = df['MILK']; print(ser_milk.head(3))
df_list = df[['FRESH', 'GROCERY']]; display(df_list.head(3))
df_slice = df.loc[:,'FRESH':'GROCERY']; display(df_slice.head(3))
df2 = df.loc[:2, 'GROCERY':]
display(df2)

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

0    9656
1    9810
2    8808
Name: MILK, dtype: int64


FRESH  GROCERY
0  12669     7561
1   7057     9568
2   6353     7684

FRESH  MILK  GROCERY
0  12669  9656     7561
1   7057  9810     9568
2   6353  8808     7684

GROCERY  FROZEN  DET_PAPER  DELICA
0     7561     214       2674    1338
1     9568    1762       3293    1776
2     7684    2405       3516    7844

### Slice (start:stop:step)  
スライスで「start : stop : step」と指定  

In [17]:
display(df.head(3))
df2 = df.loc[:, 'FRESH':'DET_PAPER':2]; display(df2.head(3))
df2 = df.loc[3:1:-1]; display(df2)

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

FRESH  GROCERY  DET_PAPER
0  12669     7561       2674
1   7057     9568       3293
2   6353     7684       3516

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
3  Horeca  Other  13265  1196     4221    6404        507    1788
2  Retail  Other   6353  8808     7684    2405       3516    7844
1  Retail  Other   7057  9810     9568    1762       3293    1776

### When columns are also specified by serial number  
列も番号で指定する場合  

In [18]:
display(df.head(3))
df2 = df.iloc[1:3, 2:6]; display(df2)

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

FRESH  MILK  GROCERY  FROZEN
1   7057  9810     9568    1762
2   6353  8808     7684    2405

### Extract only one value  
1つだけのセルの値の取り出し  

In [19]:
display(df.head(3))
val = df.at[1, 'FRESH']; print(val)
val = df.iat[1, 2]; print(val)

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

7057
7057


### Calculation between columns  
列間の演算  

In [20]:
display(df.head(3))
ser = 2*df['FRESH']+df['GROCERY']-10000
display(ser.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

0    22899
1    13682
2    10390
dtype: int64

### Calculation of statistics for a row or a column of a DataFrame  
行・列の統計量の計算  

In [21]:
display(df.head())
ser_sum_col = df.loc[:, 'FRESH':'DELICA'].sum(axis=0); print(ser_sum_col)
ser_sum_row = df.loc[:, 'FRESH':'DELICA'].sum(axis=1); print(ser_sum_row.head())

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

FRESH        5280131
MILK         2550357
GROCERY      3498562
FROZEN       1351650
DET_PAPER    1267857
DELICA        670943
dtype: int64
0    34112
1    33266
2    36610
3    27381
4    46100
dtype: int64


### Calculation of statistics of Series  
Seriesの統計量の計算  

In [22]:
ser = df['DELICA']; print(ser.mean())
print( df['DELICA'].mean() )

1524.8704545454545
1524.8704545454545


### Extract of a part of DataFrame that matches the conditions  
条件にマッチするDataFrame部分の取り出し  

Example of conditions:
- df['col']==value1  True if value of 'col' of the row is equal to value1
- df['col']>=value1  True if value of 'col' of the row is more than value1
- df['col'].str.match(r'RegularExpressionPattern')  True if value of 'col' of the row matches the RE pattern
- df['col'].isin([val1, val2, ...])  True if value of 'col' of the row is one of val1, val2, ...

In [23]:
display(df.head())
df_ret = df[ df['CHANNEL']=='Retail' ]; display(df_ret.head())
df_ret_10k = df[ (df['CHANNEL']=='Retail') & (df['FRESH']>10000) ]; display(df_ret_10k.head())
df_noret_10k = df[ ~(df['CHANNEL']=='Retail') & (df['FRESH']>10000) ]; display(df_noret_10k.head())
ser_ret_ch = df[ df['CHANNEL']=='Retail' ].loc[:, 'FRESH']; print(ser_ret_ch.head())

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
4  Retail  Other  22615  5410     7198    3915       1777    5185
5  Retail  Other   9413  8259     5126     666       1795    1451

CHANNEL REGION  FRESH   MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0   Retail  Other  12669   9656     7561     214       2674    1338
4   Retail  Other  22615   5410     7198    3915       1777    5185
6   Retail  Other  12126   3199     6975     480       3140     545
11  Retail  Other  13146   1124     4523    1420        549     497
12  Retail  Other  31714  12319    11757     287       3881    2931

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
3   Horeca  Other  13265  1196     4221    6404        507    1788
15  Horeca  Other  10253  1114     3821     397        964     412
22  Horeca  Other  31276  1917     4469    9408       2381    4334
27  Horeca  Other  14276   803     3045     485        100     518
29  Horeca  Other  43088  2100     2609    1200       1107     823

0    12669
1     7057
2     6353
4    22615
5     9413
Name: FRESH, dtype: int64


### Extract a row with the largest column value  
ある列の値が最大である行の抽出  

In [24]:
ser_max = df.loc[ df['FRESH'].idxmax() ]
print(ser_max)

CHANNEL      Horeca
REGION        Other
FRESH        112151
MILK          29627
GROCERY       18148
FROZEN        16745
DET_PAPER      4948
DELICA         8550
Name: 181, dtype: object


### Reset of index  
indexのリセット  

In [25]:
df_10k = df[ df['FRESH']>10000 ]; display(df_10k.head(3))
df_10k_rstidx = df_10k.reset_index(); display(df_10k_rstidx.head(3))
df_10k_rstidx2 = df_10k.reset_index(drop=True); display(df_10k_rstidx2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

index CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0      0  Retail  Other  12669  9656     7561     214       2674    1338
1      3  Horeca  Other  13265  1196     4221    6404        507    1788
2      4  Retail  Other  22615  5410     7198    3915       1777    5185

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Horeca  Other  13265  1196     4221    6404        507    1788
2  Retail  Other  22615  5410     7198    3915       1777    5185

### How to modify DataFrame directly  
DataFrameを直接変更するには  

In [26]:
display(df_10k.head(3))
df_10k.reset_index(drop=True, inplace=True)
display(df_10k.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Horeca  Other  13265  1196     4221    6404        507    1788
2  Retail  Other  22615  5410     7198    3915       1777    5185

### Number of kinds of values of a column and their count  
列の値の種類と個数一覧  

In [27]:
print(df['REGION'].value_counts())

Other     316
Lisbon     77
Oporto     47
Name: REGION, dtype: int64


### The number of data that
条件を満たすデータの個数

In [28]:
print( ((df['CHANNEL']=='Retail') & (df['FRESH']>10000)).sum() )

48


### Aggregation by column values  
列の値による集約  

In [29]:
df_region_max = df.groupby('REGION').max(); display(df_region_max)

CHANNEL   FRESH   MILK  GROCERY  FROZEN  DET_PAPER  DELICA
REGION                                                           
Lisbon  Retail   56083  28326    39694   18711      19410    6854
Oporto  Retail   32717  25071    67298   60869      38102    5609
Other   Retail  112151  73498    92780   36534      40827   47943

### Cross tabulation  
クロス集計  

In [30]:
df_reg_ch = pd.crosstab(df['REGION'], df['CHANNEL']); display(df_reg_ch)
df_reg_ch2 = pd.crosstab(df['REGION'], df['CHANNEL'], 
                         margins=True, normalize='columns')
display(df_reg_ch2)

CHANNEL  Horeca  Retail
REGION                 
Lisbon       59      18
Oporto       28      19
Other       211     105

CHANNEL    Horeca    Retail       All
REGION                               
Lisbon   0.197987  0.126761  0.175000
Oporto   0.093960  0.133803  0.106818
Other    0.708054  0.739437  0.718182

### Pivot table  
ピボットテーブル  

In [31]:
df_pivot = df.pivot_table(index='REGION', columns='CHANNEL', values=['FRESH', 'FROZEN'])
display(df_pivot)

FRESH                    FROZEN             
CHANNEL        Horeca       Retail       Horeca       Retail
REGION                                                      
Lisbon   12902.254237  5200.000000  3127.322034  2584.111111
Oporto   11650.535714  7289.789474  5745.035714  1540.578947
Other    13878.052133  9831.504762  3656.900474  1513.200000

### Deletion of a column  
列の削除  

In [32]:
display(df.head(3))
df2 = df.drop(columns='DET_PAPER'); display(df2.head(3))
df2 = df.drop('DET_PAPER', axis=1); display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DELICA
0  Retail  Other  12669  9656     7561     214    1338
1  Retail  Other   7057  9810     9568    1762    1776
2  Retail  Other   6353  8808     7684    2405    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DELICA
0  Retail  Other  12669  9656     7561     214    1338
1  Retail  Other   7057  9810     9568    1762    1776
2  Retail  Other   6353  8808     7684    2405    7844

### Deletion of a row  
行の削除  

In [33]:
display(df.head(3))
df2 = df.drop(index=1); display(df2.head(3))
df2 = df.drop(1); display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

### Delete rows specified by values of a column  
ある列の値によって抽出された行を削除  

In [34]:
display(df.head(4))
df2 = df.drop(df.index[ df['FRESH']>10000]); display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
5  Retail  Other   9413  8259     5126     666       1795    1451

### Another solution (extract rows that **do not** match the cond.)  
別解 (条件にマッチ**しない**行だけを取り出す)  

In [35]:
display(df.head(4))
df2 = df[ ~(df['FRESH']>10000) ]; display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
5  Retail  Other   9413  8259     5126     666       1795    1451

### Multiple rows / columns can be specified using list or slice  
リストやスライスで複数の行番号、列名を指定することもできる。  

In [36]:
df_del = df.drop(df.loc[:, 'FRESH':'GROCERY'], axis=1); display(df_del.head(3))
df_del = df.drop(df.index[1:3]); display(df_del.head(3))
df_del = df.drop(index=[1, 3], columns=['FRESH', 'GROCERY']); display(df_del.head(3))

CHANNEL REGION  FROZEN  DET_PAPER  DELICA
0  Retail  Other     214       2674    1338
1  Retail  Other    1762       3293    1776
2  Retail  Other    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
3  Horeca  Other  13265  1196     4221    6404        507    1788
4  Retail  Other  22615  5410     7198    3915       1777    5185

CHANNEL REGION  MILK  FROZEN  DET_PAPER  DELICA
0  Retail  Other  9656     214       2674    1338
2  Retail  Other  8808    2405       3516    7844
4  Retail  Other  5410    3915       1777    5185

### Addition of a row to DataFrame  
DataFrameへの列の追加  

In [37]:
df2 = df.iloc[:3].copy(); display(df2.head(3))
df2['new_col'] = pd.Series([ 2, 4, 6 ]); display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA  new_col
0  Retail  Other  12669  9656     7561     214       2674    1338        2
1  Retail  Other   7057  9810     9568    1762       3293    1776        4
2  Retail  Other   6353  8808     7684    2405       3516    7844        6

### Addition of a column to DataFrame  
行の追加  

In [38]:
df2 = df.iloc[:3].copy(); display(df2.head(3))
ser = pd.Series(['Retail','Other',0,1,2,3,4,5], index=df2.columns)
df3 = df2.append(ser, ignore_index=True); display(df3.head(4))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Retail  Other      0     1        2       3          4       5

### Concatenation of DataFrames  
First, prepare DataFrames ...  

DataFrame同士の連結   
まず元になるデータフレームを用意   

In [39]:
df1 = pd.DataFrame([[0,1,2],[3,4,5]], columns=['c1','c2','c3'])
df2 = pd.DataFrame([[1,3,5],[2,4,6]], columns=['c4','c5','c6'])
df3 = pd.DataFrame([[9,8,7],[6,5,4]], columns=['c1','c2','c3'], index=[100,101])
df4 = pd.DataFrame([[8,6,4],[9,7,5]], columns=['c4','c5','c6'], index=[100,101])
display(df1)
display(df2)
display(df3)
display(df4)

c1  c2  c3
0   0   1   2
1   3   4   5

c4  c5  c6
0   1   3   5
1   2   4   6

c1  c2  c3
100   9   8   7
101   6   5   4

c4  c5  c6
100   8   6   4
101   9   7   5

### Concatenation along column / row  
列方向に連結 / 行方向に連結  

In [40]:
df12 = pd.concat([df1,df2], axis=1); display(df12)
df13 = pd.concat([df1,df3]); display(df13)
df13_2 = pd.concat([df1,df3], ignore_index=True); display(df13_2)
df14 = pd.concat([df1,df4], axis=1); display(df14)
df4.index=df1.index
df14_2 = pd.concat([df1,df4], axis=1); display(df14_2)

c1  c2  c3  c4  c5  c6
0   0   1   2   1   3   5
1   3   4   5   2   4   6

c1  c2  c3
0     0   1   2
1     3   4   5
100   9   8   7
101   6   5   4

c1  c2  c3
0   0   1   2
1   3   4   5
2   9   8   7
3   6   5   4

c1   c2   c3   c4   c5   c6
0    0.0  1.0  2.0  NaN  NaN  NaN
1    3.0  4.0  5.0  NaN  NaN  NaN
100  NaN  NaN  NaN  8.0  6.0  4.0
101  NaN  NaN  NaN  9.0  7.0  5.0

c1  c2  c3  c4  c5  c6
0   0   1   2   8   6   4
1   3   4   5   9   7   5

### Replacement of values  
要素の値の置換  

In [41]:
display(df.head(4))
df2 = df.copy()
df2['REGION'] = df['REGION'].replace( 'Other', 'OTHER' ); display(df2.head(4))
df2['REGION'] = df['REGION'].replace( 'Oth', 'OTH', regex=True ); display(df2.head(4))
df2.at[ df2['FRESH']>9000, 'FRESH' ] = 9000; display(df2.head(4))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Horeca  Other  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  OTHER  12669  9656     7561     214       2674    1338
1  Retail  OTHER   7057  9810     9568    1762       3293    1776
2  Retail  OTHER   6353  8808     7684    2405       3516    7844
3  Horeca  OTHER  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  OTHer  12669  9656     7561     214       2674    1338
1  Retail  OTHer   7057  9810     9568    1762       3293    1776
2  Retail  OTHer   6353  8808     7684    2405       3516    7844
3  Horeca  OTHer  13265  1196     4221    6404        507    1788

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  OTHer   9000  9656     7561     214       2674    1338
1  Retail  OTHer   7057  9810     9568    1762       3293    1776
2  Retail  OTHer   6353  8808     7684    2405       3516    7844
3  Horeca  OTHer   9000  1196     4221    6404        507    1788

### Sorting  
並び替え(ソート)  

In [42]:
display(df.head(3))
df2 = df.sort_values(by=['CHANNEL','FRESH'],ascending=[True,False])
display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

CHANNEL REGION   FRESH   MILK  GROCERY  FROZEN  DET_PAPER  DELICA
181  Horeca  Other  112151  29627    18148   16745       4948    8550
125  Horeca  Other   76237   3473     7102   16538        778     918
284  Horeca  Other   68951   4411    12609    8692        751    2406

### Make dummy variables  
カテゴリー変数のダミー変数化  

In [43]:
display(df.head(3))
df2 = pd.get_dummies(df, drop_first=True); display(df2.head(3))

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA  CHANNEL_Retail  \
0  12669  9656     7561     214       2674    1338               1   
1   7057  9810     9568    1762       3293    1776               1   
2   6353  8808     7684    2405       3516    7844               1   

   REGION_Oporto  REGION_Other  
0              0             1  
1              0             1  
2              0             1

### Correlation coefficients (all by all)  
総当たりで相関係数を計算  

In [44]:
df2 = df.corr(); display(df2)

FRESH      MILK   GROCERY    FROZEN  DET_PAPER    DELICA
FRESH      1.000000  0.100510 -0.011854  0.345881  -0.101953  0.244690
MILK       0.100510  1.000000  0.728335  0.123994   0.661816  0.406368
GROCERY   -0.011854  0.728335  1.000000 -0.040193   0.924641  0.205497
FROZEN     0.345881  0.123994 -0.040193  1.000000  -0.131525  0.390947
DET_PAPER -0.101953  0.661816  0.924641 -0.131525   1.000000  0.069291
DELICA     0.244690  0.406368  0.205497  0.390947   0.069291  1.000000

### Correlation coefficients (Dataframe vs Series)  
1列対他列の相関係数を計算  

In [45]:
ser2 = df.corrwith(df['FRESH']); print(ser2)
print(ser2['FROZEN'])

FRESH        1.000000
MILK         0.100510
GROCERY     -0.011854
FROZEN       0.345881
DET_PAPER   -0.101953
DELICA       0.244690
dtype: float64
0.34588145710908025


### Correlation coefficients (Series vs Series)  
1列対1列の相関係数を計算  

In [46]:
corr3 = df['FROZEN'].corr(df['FRESH'])
print(corr3)

0.3458814571090802


### Save DataFrame as a CSV file  
encoding= is needed if encoding of the file is not utf-8.  

DataFrameをCSVファイルとして保存  
(漢字コードをshift-jisに指定した例。utf-8の場合はencoding=の指定は不要)  

In [47]:
df.to_csv('pandas_trainig_out.csv', index=False, encoding='shift-jis')

### Convert date type of Date column  
日付列を型変換

In [48]:
df_sreit=pd.read_csv('2045_2017-utf8.csv', delimiter=',', skiprows=9, header=0)
print(df_sreit['Date'].dtype)
display(df_sreit.head(3))

df_sreit['Date']=pd.to_datetime(df_sreit['Date'], format="%Y/%m/%d")
print(df_sreit['Date'].dtype)
display(df_sreit.head(3))

object


Date  Open  High   Low  Close  Vol  AdjClose
0  2017-01-04  9340  9340  9270   9270    6      9270
1  2017-01-05  9260  9340  9250   9260   22      9260
2  2017-01-06  9300  9380  9300   9380   69      9380

datetime64[ns]


Date  Open  High   Low  Close  Vol  AdjClose
0 2017-01-04  9340  9340  9270   9270    6      9270
1 2017-01-05  9260  9340  9250   9260   22      9260
2 2017-01-06  9300  9380  9300   9380   69      9380

### Time-series data  
Adding moving average line  

時系列データの取り扱い    
移動平均線の追加  

In [49]:
df_sreit['mov_ave3'] = df_sreit['AdjClose'].rolling(window=3).mean()
display(df_sreit.head())

Date  Open  High   Low  Close  Vol  AdjClose     mov_ave3
0 2017-01-04  9340  9340  9270   9270    6      9270          NaN
1 2017-01-05  9260  9340  9250   9260   22      9260          NaN
2 2017-01-06  9300  9380  9300   9380   69      9380  9303.333333
3 2017-01-10  9380  9390  9320   9370  465      9370  9336.666667
4 2017-01-11  9400  9520  9400   9490  233      9490  9413.333333

### Summary per month  
月ごとに集計

In [50]:
df_sreit_date = df_sreit.set_index('Date')
df_sreit_monthly = df_sreit_date.resample('M').mean()
display(df_sreit_monthly.head(3))

Open         High          Low        Close          Vol  \
Date                                                                          
2017-01-31  9390.769231  9421.538462  9362.307692  9387.692308   113.384615   
2017-02-28  9542.631579  9575.263158  9522.105263  9557.368421   112.263158   
2017-03-31  9651.500000  9683.000000  9626.500000  9655.500000  1536.300000   

               AdjClose     mov_ave3  
Date                                  
2017-01-31  9387.692308  9398.484848  
2017-02-28  9557.368421  9549.649123  
2017-03-31  9655.500000  9645.000000

### Normalization using the first value  
先頭の値で割って正規化

In [51]:
df_sreit['AdjClose_ratio'] = df_sreit['AdjClose'] / df_sreit.at[0, 'AdjClose']
display(df_sreit.head(3))

Date  Open  High   Low  Close  Vol  AdjClose     mov_ave3  \
0 2017-01-04  9340  9340  9270   9270    6      9270          NaN   
1 2017-01-05  9260  9340  9250   9260   22      9260          NaN   
2 2017-01-06  9300  9380  9300   9380   69      9380  9303.333333   

   AdjClose_ratio  
0        1.000000  
1        0.998921  
2        1.011866

### Number of days since Jan 1st, 2017  
2017年1月1日からの日数(2017年1月1日を1日目とする)を「2017年日数」列として追加

In [52]:
day1 = pd.to_datetime('2017-01-01')
dayw = np.timedelta64(1, 'D')
df_sreit['ndays2017'] = (df_sreit['Date']-day1) / dayw + 1
display(df_sreit.head(3))

# Another solution (別解)
df_sreit['ndays2017'] = (df_sreit['Date']-day1).dt.days + 1
display(df_sreit.head(3))

Date  Open  High   Low  Close  Vol  AdjClose     mov_ave3  \
0 2017-01-04  9340  9340  9270   9270    6      9270          NaN   
1 2017-01-05  9260  9340  9250   9260   22      9260          NaN   
2 2017-01-06  9300  9380  9300   9380   69      9380  9303.333333   

   AdjClose_ratio  ndays2017  
0        1.000000        4.0  
1        0.998921        5.0  
2        1.011866        6.0

Date  Open  High   Low  Close  Vol  AdjClose     mov_ave3  \
0 2017-01-04  9340  9340  9270   9270    6      9270          NaN   
1 2017-01-05  9260  9340  9250   9260   22      9260          NaN   
2 2017-01-06  9300  9380  9300   9380   69      9380  9303.333333   

   AdjClose_ratio  ndays2017  
0        1.000000          4  
1        0.998921          5  
2        1.011866          6

### Merge DataFrames  
データフレームのマージ  

In [53]:
df_sreit=pd.read_csv('2045_2017-utf8.csv', delimiter=',', skiprows=9, header=0)
df_sreit['Date']=pd.to_datetime(df_sreit['Date'], format="%Y/%m/%d")
display(df_sreit.head(3))

df_ubs=pd.read_csv('1393_2017-utf8.csv', delimiter=',', skiprows=9, header=0)
df_ubs['Date']=pd.to_datetime(df_ubs['Date'], format="%Y/%m/%d")
display(df_ubs.head(3))

df_merged = pd.merge(df_sreit, df_ubs, on='Date', how='inner'); display(df_merged.head(3))

Date  Open  High   Low  Close  Vol  AdjClose
0 2017-01-04  9340  9340  9270   9270    6      9270
1 2017-01-05  9260  9340  9250   9260   22      9260
2 2017-01-06  9300  9380  9300   9380   69      9380

Date   Open   High    Low  Close  Vol  AdjClose
0 2017-01-04  25500  25520  25410  25520   21     25520
1 2017-01-05  25520  25520  25200  25220   71     25220
2 2017-01-06  25150  25170  25150  25170    3     25170

Date  Open_x  High_x  Low_x  Close_x  Vol_x  AdjClose_x  Open_y  \
0 2017-01-04    9340    9340   9270     9270      6        9270   25500   
1 2017-01-05    9260    9340   9250     9260     22        9260   25520   
2 2017-01-06    9300    9380   9300     9380     69        9380   25150   

   High_y  Low_y  Close_y  Vol_y  AdjClose_y  
0   25520  25410    25520     21       25520  
1   25520  25200    25220     71       25220  
2   25170  25150    25170      3       25170

### Read CSV file with missing values  
欠損値がある場合  

In [54]:
df_missing = pd.read_csv('pandas_training_missing-utf8.csv',
                                  delimiter=',', skiprows=13, header=0)
display(df_missing.head(3))

CHANNEL REGION   FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other     NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other  7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other  6353.0  8808     7684  2405.0       3516  7844.0

### Check missing values  
欠損値のチェック

In [55]:
print( df_missing.isnull().sum() )
display( df_missing[ df_missing.isnull().any(axis=1) ] )

CHANNEL      0
REGION       0
FRESH        1
MILK         0
GROCERY      0
FROZEN       1
DET_PAPER    0
DELICA       1
dtype: int64


CHANNEL REGION   FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other     NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other  7057.0  9810     9568  1762.0       3293     NaN

### Delete / Fill missing values  
欠損値を削除する・埋める

In [56]:
display(df_missing.head(3))
df_del = df_missing.dropna(axis=0); display(df_del.head(3))
df_del = df_missing.dropna(axis=0).reset_index(drop=True); display(df_del.head(3))
df_del = df_missing.dropna(subset=['DELICA'], axis=0); display(df_del.head(3))
df_filled = df_missing.fillna(df_missing.mean()); display(df_filled.head(3))

CHANNEL REGION   FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other     NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other  7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other  6353.0  8808     7684  2405.0       3516  7844.0

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0
4  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
1  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0
2  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other      NaN  9656     7561     NaN       2674  1338.0
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0

CHANNEL REGION         FRESH  MILK  GROCERY       FROZEN  DET_PAPER  \
0  Retail  Other  11998.774487  9656     7561  3078.441913       2674   
1  Retail  Other   7057.000000  9810     9568  1762.000000       3293   
2  Retail  Other   6353.000000  8808     7684  2405.000000       3516   

        DELICA  
0  1338.000000  
1  1524.298405  
2  7844.000000

### Extract duplicated lines  
重複行の抽出    

In [57]:
# Make duplicated DataFrame
df_dup = df.iloc[:3].copy()
df_dup = df_dup.append(df.loc[1]).reset_index(drop=True)
display(df_dup)
# Extract duplicated rows
display(df_dup[ df_dup.duplicated() ])

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844
3  Retail  Other   7057  9810     9568    1762       3293    1776

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
3  Retail  Other   7057  9810     9568    1762       3293    1776

### Delete duplicated lines  
重複行の削除    

In [58]:
df_nodup = df_dup.drop_duplicates().reset_index(drop=True)
display(df_nodup)

CHANNEL REGION  FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other  12669  9656     7561     214       2674    1338
1  Retail  Other   7057  9810     9568    1762       3293    1776
2  Retail  Other   6353  8808     7684    2405       3516    7844

### Why should we use functions of numpy / pandas?  
なぜ numpy / pandas の関数を使うのか？  

In [59]:
%%time
a_for = np.empty( (5000, 5000) )
for i in range(5000):
    for j in range(5000):
        a_for[i, j] = 1.0

Wall time: 10.7 s


In [60]:
%%time
b_np = np.ones( (5000, 5000) )

Wall time: 275 ms
