In [97]:
import numpy as np
import pandas as pd

In [98]:
nums = np.array([1 ,2, 3, 5, 6, 7, 8, 9, 10])
print(nums)

[ 1  2  3  5  6  7  8  9 10]


+ Create an array without initializing entries.
    + A = np.empty(5) → a 1d array with 5 elements (random values)
    + A = np.empty((2,3)) → a 3x2 2d array (random values)
+ Create an array and initialize entries.
    + A = np.zeros((2,3)) → a 2x3 2d array setting values to zero
    + A = np.ones((2,3)) → a 2x3 2d array setting values to one
    + A = np.identity(3) → a 3x3 2d identity array with its main diagonal set to one, and all other elements 0.

In [99]:
# Range and reshape
nums1d = np.arange(15)
nums2d = nums1d.reshape(-1,3)
print(nums1d)
print(nums2d)

nums1d = np.arange(1, 16)
nums2d = nums1d.reshape(-1,3)
print(nums1d)
print(nums2d)

nums1d = np.arange(0, 7.5, 0.5)
nums2d = nums1d.reshape(-1,3)
print(nums1d)
print(nums2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]
 [4.5 5.  5.5]
 [6.  6.5 7. ]]


In [100]:
# Matrix Multilication
nums1 = np.arange(6).reshape(2, 3)
nums2 = np.arange(6).reshape(3, 2)
nums3 = np.dot(nums1, nums2)
print(nums1)
print(nums2)
print(nums3)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]


In [101]:
nums1 = np.arange(10)
nums2 = nums1
nums3 = nums1.copy()
nums1[1] = 2
nums1[0] = 2
print(nums1)
print(nums2)
print(nums3)

[2 2 2 3 4 5 6 7 8 9]
[2 2 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


## Computation of Statistical Measurements

+ Let dat be a 2d array:
    + np.function(dat, axis=0) ←Column-wise statistic
    + np.function(dat, axis=1) ←Row-wise statistic
+ Example of「function」
    + the minimum of an array: amin
    + the maximum of an array: amax
    + the average of an array: mean
    + the median of an array: median
    + standard deviation (population) of an array: std
    + summation of an array: sum
    + Compute unbiased standard deviation, using np.std(dat, ddof=1, axis=0)

In [102]:
nums = np.arange(20).reshape(4, 5)
print(nums)
print(np.amin(nums, axis=0))
print(np.amin(nums, axis=1))
print(np.median(nums, axis=1))
print(np.sum(nums, axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[ 0  5 10 15]
[ 2.  7. 12. 17.]
[30 34 38 42 46]


In [103]:
df = pd.read_csv('pandas_training_missing-utf8.csv', delimiter=',', skiprows=13, header=0)
display(df.head(5))
display(df['MILK'])
display(df.loc[2])

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other      NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other   7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0
4  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0

0       9656
1       9810
2       8808
3       1196
4       5410
       ...  
435    12051
436     1431
437    15488
438     1981
439     1698
Name: MILK, Length: 440, dtype: int64

CHANNEL      Retail
REGION        Other
FRESH          6353
MILK           8808
GROCERY        7684
FROZEN         2405
DET_PAPER      3516
DELICA         7844
Name: 2, dtype: object

In [104]:
df2 = df.iloc[1:100, 2:6]
display(df2.head())
display(df2.sum(axis=0))
df2 = df.loc[1:100, 'FRESH':'DELICA']
display(df2.head())
display(df2.sum(axis=0))

FRESH  MILK  GROCERY  FROZEN
1   7057.0  9810     9568  1762.0
2   6353.0  8808     7684  2405.0
3  13265.0  1196     4221  6404.0
4  22615.0  5410     7198  3915.0
5   9413.0  8259     5126   666.0

FRESH      1283078.0
MILK        823052.0
GROCERY    1107560.0
FROZEN      281344.0
dtype: float64

FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
1   7057.0  9810     9568  1762.0       3293     NaN
2   6353.0  8808     7684  2405.0       3516  7844.0
3  13265.0  1196     4221  6404.0        507  1788.0
4  22615.0  5410     7198  3915.0       1777  5185.0
5   9413.0  8259     5126   666.0       1795  1451.0

FRESH        1294672.0
MILK          830831.0
GROCERY      1119704.0
FROZEN        284596.0
DET_PAPER     451189.0
DELICA        200697.0
dtype: float64

In [105]:
 print(df.iat[1, 2], df.at[1, 'FRESH'])

7057.0 7057.0


## Examples of Conditions for Row/Column Extraction from DataFrame: df_part = df\[Cond.\]
+ df\['ColName'\]==Val1
    + Rows whose values in column "ColName" are consistent with Val1.
+ df\['ColName'\]>Val1
    + Rows whose values in column "ColName" are larger than Val1.
+ df\['ColName'\].str.match(r'Regex')
    + Rows whose values in column "ColName" match with a regular expression "Regex".
+ df\['ColName'\].isin(\['Val1', 'Val2', ...\])
    +Rows whose values in column "ColName" are either Val1, Val2, etc

In [106]:
# Select a Subset of a DataFrame with Conditions
df_ret = df[ df['CHANNEL']=='Retail' ]
display(df_ret.head())
df_ret = df[ (df['MILK']<2000) & (df['CHANNEL']=='Retail') ]
display(df_ret.head(10))
df_ret = df[ (df['MILK']<2000) & ~(df['CHANNEL']=='Retail') ]
display(df_ret.head(10))
display((df['MILK']<2000) & (df['CHANNEL']=='Retail'))

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other      NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other   7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
4  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0
5  Retail  Other   9413.0  8259     5126   666.0       1795  1451.0

CHANNEL  REGION    FRESH  MILK  GROCERY   FROZEN  DET_PAPER  DELICA
11   Retail   Other  13146.0  1124     4523   1420.0        549   497.0
295  Retail  Oporto   7588.0  1897     5234    417.0       2208   254.0
334  Retail  Oporto  16823.0   928     2743  11559.0        332  3486.0
357  Retail   Other     37.0  1275    22272    137.0       6747   110.0

CHANNEL REGION    FRESH  MILK  GROCERY   FROZEN  DET_PAPER  DELICA
3   Horeca  Other  13265.0  1196     4221   6404.0        507  1788.0
15  Horeca  Other  10253.0  1114     3821    397.0        964   412.0
21  Horeca  Other   5567.0   871     2010   3383.0        375   569.0
22  Horeca  Other  31276.0  1917     4469   9408.0       2381  4334.0
26  Horeca  Other   9898.0   961     2861   3151.0        242   833.0
27  Horeca  Other  14276.0   803     3045    485.0        100   518.0
32  Horeca  Other  21632.0  1318     2886    266.0        918   405.0
34  Horeca  Other   1502.0  1979     2262    425.0        483   395.0
39  Horeca  Other  56159.0   555      902  10002.0        212  2916.0
50  Horeca  Other   6269.0  1095     1980   3860.0        609  2162.0

0      False
1      False
2      False
3      False
4      False
       ...  
435    False
436    False
437    False
438    False
439    False
Length: 440, dtype: bool

In [113]:
# Page 47 OK
df_test = df.iloc[0:5, :]
display(df_test)
display(df_test[ df_test['MILK']<5000 ])
display(df_test[ df_test['MILK']<5000 ].reset_index(drop=True, inplace=True))
df_test_child1 = df_test[ df_test['MILK']<5000 ].reset_index(drop=True, inplace=True)
df_test_child2 = df_test[ df_test['MILK']<5000 ].reset_index(drop=True, inplace=False)
display(df_test_child1)
#df_test_child1.at[0, 'FRESH']
display(df_test)


CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other      NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other   7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0
4  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0

None

None

CHANNEL REGION    FRESH  MILK  GROCERY  FROZEN  DET_PAPER  DELICA
0  Retail  Other      NaN  9656     7561     NaN       2674  1338.0
1  Retail  Other   7057.0  9810     9568  1762.0       3293     NaN
2  Retail  Other   6353.0  8808     7684  2405.0       3516  7844.0
3  Horeca  Other  13265.0  1196     4221  6404.0        507  1788.0
4  Retail  Other  22615.0  5410     7198  3915.0       1777  5185.0