In [1]:
import numpy as np

In [2]:
v1 = np.array([1.0, 3.0, 5.0, 3.0, 1.0])
print(v1)

[1. 3. 5. 3. 1.]


In [3]:
v2 = np.linspace(-1, 1, num=5)
print(v2)

[-1.  -0.5  0.   0.5  1. ]


In [4]:
v3 = v1 + v2
print(v3)

[0.  2.5 5.  3.5 2. ]


In [5]:
v4 = np.arange(1, 9)
print(v4)

[1 2 3 4 5 6 7 8]


In [8]:
v5 = v4.reshape(2, 4)
print(v5)
print(v5.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [11]:
print(np.amin(v5, axis=1))
print(np.sum(v5, axis=0))

[1 5]
[ 6  8 10 12]
