In [18]:
# Import
import numpy as np

In [19]:
# About array
npArray = np.array([1,5,8,9,10,4,6]);
npArrayCloce1 = npArray
npArrayCloce2 = npArray.copy()
npArray.sort()
print(npArray)
print(npArrayCloce1)
print(npArrayCloce2)

[ 1  4  5  6  8  9 10]
[ 1  4  5  6  8  9 10]
[ 1  5  8  9 10  4  6]


In [20]:
# Array take some elements satisfy condition
npArray = np.array([1,5,8,9,10,4,6]);
print(npArray[npArray>5])

[ 8  9 10  6]
