### DM-04 Practice 1  

In [36]:
import numpy as np
import pandas as pd
import scipy.stats as ss

**1.**

In [37]:
csv_in = 'dm-04-practice1-1.csv'
df1 = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df1.shape)
print(df1.info())
display(df1.head())

(20, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   ID        20 non-null     int64 
 1   Strategy  20 non-null     object
 2   Score     20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes
None


ID Strategy  Score
0   1        A     69
1   2        A     59
2   3        A     58
3   4        A     47
4   5        A     60

In [38]:
df1_A = df1[ df1['Strategy'] == 'A' ]
df1_B = df1[ df1['Strategy'] == 'B' ]
print(df1_A['Score'].mean(), df1_B['Score'].mean())
t, p = ss.ttest_ind(df1_A['Score'], df1_B['Score'], equal_var=False)
print(t, p/2)

58.7 69.6
-4.650124757777125 0.00010506259959873132


**(Conclusion): t < 0 (i.e. average of A < average of B) and p/2 < 0.05, so population mean of B is significantly better than that of A. Strategy B is significantly better than strategy A.  
(結論): t < 0 (つまり Aの母平均 < Bの母平均) かつ p/2 < 0.05 なので、Bの母平均はAの母平均よりも有意に高い。よって「新戦法Bは有意に有効」といえる。**

**2.**

In [39]:
csv_in = 'dm-04-practice1-2.csv'
df2 = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df2.shape)
print(df2.info())
display(df2.head())

(20, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   ID        20 non-null     int64 
 1   Strategy  20 non-null     object
 2   Score     20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 608.0+ bytes
None


ID Strategy  Score
0   1        A     56
1   2        A     54
2   3        A     63
3   4        A     59
4   5        A     65

In [40]:
df2_A = df2[ df2['Strategy'] == 'A' ]
df2_B = df2[ df2['Strategy'] == 'B' ]
print(df2_A['Score'].mean(), df2_B['Score'].mean())
t, p = ss.ttest_ind(df2_A['Score'], df2_B['Score'], equal_var=False)
print(t, p)

61.4 62.5
-0.5404029961335236 0.5955912875934701


**(Conclusion): p > 0.05, so population means of A, B are NOT significantly different.  
(結論): p < 0.05 なので、A, Bの母平均は有意に異なるとはいえない。よって「戦法A, Bの効果は有意に異なる」といえない。**

**3.**  

In [41]:
csv_in = 'dm-04-practice1-3.csv'
df3 = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df3.shape)
print(df3.info())
display(df3.head())

(10, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   ScoreA  10 non-null     int64
 2   ScoreB  10 non-null     int64
dtypes: int64(3)
memory usage: 368.0 bytes
None


ID  ScoreA  ScoreB
0   1      61      71
1   2      51      66
2   3      63      51
3   4      66      59
4   5      65      63

In [42]:
print((df3['ScoreA']-df3['ScoreB']).mean())
t, p = ss.ttest_1samp(df3['ScoreA']-df3['ScoreB'], 0.0)
print(t, p/2)

1.1
0.3412961270145238 0.3703567859203507


**(Conclusion): p/2 > 0.05, so population means of A-B are NOT significantly positive.  
(結論): p/2 < 0.05 なので、A-Bの母平均は有意に0より大であるとはいえない。よって「戦法Aは戦法Bよりも有意によい」といえない。**

**4.**  

In [43]:
csv_in = 'dm-04-practice1-4.csv'
df4 = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df4.shape)
print(df4.info())
display(df4.head())

(100, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  100 non-null    int64
dtypes: int64(1)
memory usage: 928.0 bytes
None


Weight
0     151
1     148
2     147
3     148
4     147

In [44]:
t, p = ss.ttest_1samp(df4['Weight'], 150.0)
print(t, p)

0.3932491054717222 0.6949810784688064


**(Conclusion) p > 0.05, so population mean of the weight is NOT significantly different from 150g.  
(結論) 重さの母平均は「有意に150gでない」とはいえない。**  

**5.**  

In [45]:
csv_in = 'dm-04-practice1-5.csv'
df5 = pd.read_csv(csv_in, delimiter=',', skiprows=0, header=0)
print(df5.shape)
print(df5.info())
display(df5.head())

(100, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ID          100 non-null    int64 
 1   Generation  100 non-null    object
 2   Favorite    100 non-null    object
dtypes: int64(1), object(2)
memory usage: 2.5+ KB
None


ID Generation Favorite
0   1       U-30        C
1   2       O-50        A
2   3       U-20        A
3   4       U-30        B
4   5       U-40        C

In [46]:
cross_tab = pd.crosstab(df5['Generation'], df5['Favorite'])
display(cross_tab)

Favorite     A   B  C
Generation           
O-50        13  10  4
U-20        11  15  6
U-30         4   9  3
U-40         5  14  6

In [48]:
chi2, p, dof, expected = ss.chi2_contingency(cross_tab)
print(chi2, p, dof)
print(expected)

5.310521608630161 0.5046467737517948 6
[[ 8.91 12.96  5.13]
 [10.56 15.36  6.08]
 [ 5.28  7.68  3.04]
 [ 8.25 12.    4.75]]


**(Conclusion) p > 0.05, so "Generation" and "Favorite (design)" are not significantly related.  
(結論) 「世代」と「好きなデザイン」は有意に関連しているとはいえない。**